{
 "title": "TESTING_DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "calm_IDF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(entity_stats{metric=\"mem\"}) by (entity_type)",
     "legendFormat": "{{entity_type}}"
    }
   ]
  },
  {
   "title": "#No.of entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(entity_stats{metric=\"entities\"}) by (entity_type)",
     "legendFormat": "{{entity_type}}"
    }
   ]
  },
  {
   "title": "idf_resident_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "idf_res_mem", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "epsilon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "epsilon_engine:vajra_0_cpu_usage_percent",
     "legendFormat": "vajra_0"
    },
    {
     "expr": "home_epsilon_bin_arjun___worker_id_0_cpu_usage_percent",
     "legendFormat": "arjun_0"
    },
    {
     "expr": "home_epsilon_bin_arjun___worker_id_1_cpu_usage_percent",
     "legendFormat": "arjun1"
    },
    {
     "expr": "home_epsilon_bin_durga___worker_id_0_cpu_usage_percent",
     "legendFormat": "durga_0"
    },
    {
     "expr": "home_epsilon_bin_durga___worker_id_1_cpu_usage_percent",
     "legendFormat": "durga_1"
    },
    {
     "expr": "home_epsilon_bin_indra___worker_id_0_cpu_usage_percent",
     "legendFormat": "indra_0"
    },
    {
     "expr": "home_epsilon_bin_indra___worker_id_1_cpu_usage_percent",
     "legendFormat": "indra_1"
    },
    {
     "expr": "home_epsilon_bin_jove_cpu_usage_percent",
     "legendFormat": "jove"
    },
    {
     "expr": "home_epsilon_bin_karan___worker_id_0_cpu_usage_percent",
     "legendFormat": "karan_0"
    },
    {
     "expr": "home_epsilon_bin_karan___worker_id_0_cpu_usage_percent",
     "legendFormat": "karan_1"
    },
    {
     "expr": "home_epsilon_bin_narad_cpu_usage_percent",
     "legendFormat": "narad"
    },
    {
     "expr": "home_epsilon_bin_zaffi_cpu_usage_percent",
     "legendFormat": "zaffi"
    },
    {
     "expr": "home_epsilon_conf_modules_proxy_service_ini_cpu_usage_percent",
     "legendFormat": "proxy_service"
    },
    {
     "expr": "elastic_search_cpu_usage_percent",
     "legendFormat": "elastic_search"
    },
    {
     "expr": "usr_bin_redis_serve_cpu_usage_percent",
     "legendFormat": "redis"
    },
    {
     "expr": "var_lib_pgsql_11_data_postgresql_conf_cpu_usage_percent",
     "legendFormat": "postgres"
    },
    {
     "expr": "sum(proxy_child_stats{metric=\"cpu_usage\"}) by (pid)",
     "legendFormat": "proxy_child_{{child}}"
    }
   ]
  },
  {
   "title": "MEM (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "vajra_0_memory_mb", "legendFormat": "vajra_0" },
    {
     "expr": "home_epsilon_bin_arjun___worker_id_0_memory_mb",
     "legendFormat": "arjun_0"
    },
    {
     "expr": "home_epsilon_bin_arjun___worker_id_1_memory_mb",
     "legendFormat": "arjun1"
    },
    {
     "expr": "home_epsilon_bin_durga___worker_id_0_memory_mb",
     "legendFormat": "durga_0"
    },
    {
     "expr": "home_epsilon_bin_durga___worker_id_1_memory_mb",
     "legendFormat": "durga_1"
    },
    {
     "expr": "home_epsilon_bin_indra___worker_id_0_memory_mb",
     "legendFormat": "indra_0"
    },
    {
     "expr": "home_epsilon_bin_indra___worker_id_1_memory_mb",
     "legendFormat": "indra_1"
    },
    {
     "expr": "home_epsilon_bin_jove_memory_mb",
     "legendFormat": "jove"
    },
    {
     "expr": "home_epsilon_bin_karan___worker_id_0_memory_mb",
     "legendFormat": "karan_0"
    },
    {
     "expr": "home_epsilon_bin_karan___worker_id_1_memory_mb",
     "legendFormat": "karan_1"
    },
    {
     "expr": "home_epsilon_bin_narad_memory_mb",
     "legendFormat": "narad"
    },
    {
     "expr": "home_epsilon_bin_zaffi_memory_mb",
     "legendFormat": "zaffi"
    },
    {
     "expr": "home_epsilon_conf_modules_proxy_service_ini_memory_mb",
     "legendFormat": "proxy_service"
    },
    { "expr": "elastic_search_memory_mb", "legendFormat": "elastic_search" },
    { "expr": "usr_bin_redis_serve_memory_mb", "legendFormat": "redis" },
    { "expr": "usr_bin_redis_serve_memory_mb", "legendFormat": "redis" },
    {
     "expr": "var_lib_pgsql_11_data_postgresql_conf_memory_mb",
     "legendFormat": "postgres"
    },
    {
     "expr": "sum(proxy_child_stats{metric=\"res_mem\"}) by (pid)",
     "legendFormat": "proxy_child_{{pid}}"
    }
   ]
  },
  {
   "title": "MEM %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "epsilon_engine:vajra_0_memory_usage_percent",
     "legendFormat": "vajra_0"
    },
    {
     "expr": "home_epsilon_bin_arjun___worker_id_0_memory_usage_percent",
     "legendFormat": "arjun_0"
    },
    {
     "expr": "home_epsilon_bin_arjun___worker_id_1_memory_usage_percent",
     "legendFormat": "arjun1"
    },
    {
     "expr": "home_epsilon_bin_durga___worker_id_0_memory_usage_percent",
     "legendFormat": "durga_0"
    },
    {
     "expr": "home_epsilon_bin_durga___worker_id_1_memory_usage_percent",
     "legendFormat": "durga_1"
    },
    {
     "expr": "home_epsilon_bin_indra___worker_id_0_memory_usage_percent",
     "legendFormat": "indra_0"
    },
    {
     "expr": "home_epsilon_bin_indra___worker_id_1_memory_usage_percent",
     "legendFormat": "indra_1"
    },
    {
     "expr": "home_epsilon_bin_jove_memory_usage_percent",
     "legendFormat": "jove"
    },
    {
     "expr": "home_epsilon_bin_karan___worker_id_0_memory_usage_percent",
     "legendFormat": "karan_0"
    },
    {
     "expr": "home_epsilon_bin_karan___worker_id_1_memory_usage_percent",
     "legendFormat": "karan_1"
    },
    {
     "expr": "home_epsilon_bin_narad_memory_usage_percent",
     "legendFormat": "narad"
    },
    {
     "expr": "home_epsilon_bin_zaffi_memory_usage_percent",
     "legendFormat": "zaffi"
    },
    {
     "expr": "home_epsilon_conf_modules_proxy_service_ini_memory_usage_percent",
     "legendFormat": "proxy_service"
    },
    {
     "expr": "elastic_search_memory_usage_percent",
     "legendFormat": "elastic_search"
    },
    {
     "expr": "usr_bin_redis_serve_memory_usage_percent",
     "legendFormat": "redis"
    },
    {
     "expr": "var_lib_pgsql_11_data_postgresql_conf_memory_usage_percent",
     "legendFormat": "postgres"
    },
    {
     "expr": "sum(proxy_child_stats{metric=\"mem_usage\"}) by (pid)",
     "legendFormat": "proxy_child_{{pid}}"
    }
   ]
  },
  { "title": "SelfService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hercules_app_pyc___process_num_0_cpu_usage_percent",
     "legendFormat": "hercules_0"
    },
    {
     "expr": "hercules_app_pyc___process_num_1_cpu_usage_percent",
     "legendFormat": "hercules_1"
    },
    {
     "expr": "_home_calm_bin_algalon_cpu_usage_percent",
     "legendFormat": "algalon"
    },
    {
     "expr": "_home_calm_bin_eos_cpu_usage_percent",
     "legendFormat": "eos"
    },
    {
     "expr": "_home_calm_bin_goiris_cpu_usage_percent",
     "legendFormat": "goiris"
    },
    {
     "expr": "_home_calm_bin_helios_cpu_usage_percent",
     "legendFormat": "helios"
    },
    {
     "expr": "_home_calm_bin_jove_cpu_usage_percent",
     "legendFormat": "jove"
    },
    {
     "expr": "calm_server_styx_cpu_usage_percent",
     "legendFormat": "styx"
    },
    {
     "expr": "sum(styx_child_stats{metric=\"cpu_usage\"}) by (pid)",
     "legendFormat": "styx_child_{{pid}}"
    }
   ]
  },
  {
   "title": "MEM (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "hercules_app_pyc___process_num_0_memory_mb",
     "legendFormat": "hercules_0"
    },
    {
     "expr": "hercules_app_pyc___process_num_1_memory_mb",
     "legendFormat": "hercules_1"
    },
    {
     "expr": "_home_calm_bin_algalon_memory_mb",
     "legendFormat": "algalon"
    },
    { "expr": "_home_calm_bin_eos_memory_mb", "legendFormat": "eos" },
    {
     "expr": "_home_calm_bin_goiris_memory_mb",
     "legendFormat": "goiris"
    },
    {
     "expr": "_home_calm_bin_helios_memory_mb",
     "legendFormat": "helios"
    },
    { "expr": "_home_calm_bin_jove_memory_mb", "legendFormat": "jove" },
    { "expr": "calm_server_styx_memory_mb", "legendFormat": "styx" },
    {
     "expr": "sum(styx_child_stats{metric=\"res_mem\"}) by (pid)",
     "legendFormat": "styx_{{pid}}"
    }
   ]
  },
  {
   "title": "MEM %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hercules_app_pyc___process_num_0_memory_usage_percent",
     "legendFormat": "hercules_0"
    },
    {
     "expr": "hercules_app_pyc___process_num_1_memory_usage_percent",
     "legendFormat": "hercules_1"
    },
    {
     "expr": "_home_calm_bin_algalon_memory_usage_percent",
     "legendFormat": "algalon"
    },
    {
     "expr": "_home_calm_bin_eos_memory_usage_percent",
     "legendFormat": "eos"
    },
    {
     "expr": "_home_calm_bin_goiris_memory_usage_percent",
     "legendFormat": "goiris"
    },
    {
     "expr": "_home_calm_bin_helios_memory_usage_percent",
     "legendFormat": "helios"
    },
    {
     "expr": "_home_calm_bin_jove_memory_usage_percent",
     "legendFormat": "jove"
    },
    {
     "expr": "calm_server_styx_memory_usage_percent",
     "legendFormat": "styx"
    },
    {
     "expr": "sum(styx_child_stats{metric=\"mem_usgae\"}) by (pid)",
     "legendFormat": "styx_child_{{pid}}"
    }
   ]
  }
 ]
}