apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  name: ubuntu-pod-latest
  namespace: default
  labels:  # Add labels here
    app.kubernetes.io/instance: ubuntu-pod
    app.kubernetes.io/name: ubuntu-pod-nodeport
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - "cp /host/.kube/config /home/.kube/ && /usr/local/bin/python3.9 /home/scripts/expose_metrics.py"
      image: ubuntu:v22
      imagePullPolicy: IfNotPresent
      name: ubuntu-container
      volumeMounts:
        - name: host-files
          mountPath: /var/nutanix/etc/kubernetes/ssl/
        - name: host-kube-config
          mountPath: /host/.kube
        - name: kubectl-config
          mountPath: /home/.kube/
      ports:
        - containerPort: 8009
  volumes:
    - name: host-files
      hostPath:
        path: /var/nutanix/etc/kubernetes/ssl  # Path on the host
        type: Directory
    - name: host-kube-config
      hostPath:
        path: /home/nutanix/.kube
        type: Directory
    - name: kubectl-config
      emptyDir: {}
