[supervisord]
nodaemon=true

[program:script1]
command=/home/mohan.as/mohan_helpers/test_docker/hello.py
autorestart=true
autoretry=true
startretries=3
stdout_logfile=/home/mohan.as/mohan_helpers/test_docker/hello.log
stderr_logfile=/home/mohan.as/mohan_helpers/test_docker/hello_err.log
healthcheck_script=/usr/local/bin/healthcheck.sh hello.py
